version: '3.7'

networks:
  hanyang-chatbot:

services:
  flask:
    restart: always
    build: '.'
    volumes:
      - type: bind
        source: ./
        target: /app
    environment:
      env: "production"
    networks:
      - hanyang-chatbot
    ports:
      - '5000:5000'
    entrypoint: ['python', 'app.py']
    depends_on:
      - mongo
  mongo:
    restart: always
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - type: bind
        source: ./mongo/data
        target: /data/db
      - type: bind
        source: ./mongo/namu_wiki
        target: /dataset
    networks:
      - hanyang-chatbot
  nginx:
    restart: always
    image: nginx:${NGINX_VERSION:-latest}
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./cert:/etc/certs
    depends_on:
      - flask
    networks:
      - hanyang-chatbot 
