version: "3"

services:
  server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint:
      - python3
    command:
      - app.py

  mongod:
    image: mongo:latest
    restart: always
    volumes:
      - /mnt/data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
